[package]
name = "skreaver-workspace"
version = "0.1.0"
edition = "2024"
authors = ["Oleksandr Husiev <ohusiev@icloud.com>"]
license = "MIT"
description = "Skreaver — Rust-based open agentic infrastructure platform"
repository = "https://github.com/shurankain/skreaver"
homepage = "https://ohusiev.com"
keywords = ["agent", "infrastructure", "ai", "rust"]
categories = ["development-tools", "ai"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
redis = { version = "0.32.4", features = ["tokio-comp"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "sync", "time"] }
uuid = { version = "1", features = ["v4"] }
tracing = "0.1"
humantime = "2.1"
thiserror = "1.0"
# Examples dependencies (only loaded when running examples)
axum = { version = "0.7", features = ["macros"] }
tower-http = { version = "0.5", features = ["cors"] }
chrono = { version = "0.4", features = ["serde"] }
# Core crates
skreaver-core = { path = "crates/skreaver-core" }
skreaver-memory = { path = "crates/skreaver-memory" }
skreaver-tools = { path = "crates/skreaver-tools" }
skreaver-http = { path = "crates/skreaver-http" }
# Meta crate for examples
skreaver = { path = "crates/skreaver", features = ["testing"] }

# Benchmarking dependencies  
[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"
rand = "0.8"
skreaver-testing = { path = "crates/skreaver-testing" }
# Only for benchmarks - not compiled in normal builds
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }

[workspace]
members = ["skreaver-cli", "crates/skreaver-core", "crates/skreaver-memory", "crates/skreaver-tools", "crates/skreaver-http", "crates/skreaver-testing", "crates/skreaver"]
resolver = "2"

# Benchmark configuration
[[bench]]
name = "simple_benchmarks" 
harness = false

[[bench]]
name = "realistic_benchmarks"
harness = false

[[bench]]
name = "comprehensive_benchmark"
harness = false

[[bench]]
name = "optimized_benchmark"
harness = false

[[bench]]
name = "quick_benchmark"
harness = false