[package]
name = "skreaver"
version = "0.1.0"
edition = "2024"
authors = ["Oleksandr Husiev <ohusiev@icloud.com>"]
license = "MIT"
description = "Skreaver — Rust-based open agentic infrastructure platform"
repository = "https://github.com/shurankain/skreaver"
homepage = "https://ohusiev.com"
keywords = ["agent", "infrastructure", "ai", "rust"]
categories = ["development-tools", "ai"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
redis = { version = "0.32.4", features = ["tokio-comp", "json"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
tracing = "0.1"
humantime = "2.1"
thiserror = "1.0"
# Standard tools dependencies
reqwest = { version = "0.12", features = ["json"] }
quick-xml = { version = "0.36", features = ["serialize"] }
# HTTP runtime dependencies
axum = { version = "0.7", features = ["macros"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "timeout", "limit"] }
chrono = { version = "0.4", features = ["serde"] }
# Authentication and security
jsonwebtoken = "9.0"
once_cell = "1.0"
# Rate limiting
governor = "0.6"
# Streaming and async
futures = "0.3"
tokio-stream = "0.1"
# OpenAPI documentation
utoipa = { version = "4.0", features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { version = "4.0", features = ["axum"] }
# Security and validation
regex = "1.0"
html-escape = "0.2"
base64 = "0.21"
rand = "0.8"

[workspace]
members = [".", "skreaver-cli"]
