# cargo-deny configuration for Skreaver
# Security scanning, license validation, and dependency management
#
# This configuration enforces:
# - Security vulnerability detection (advisories)
# - License compliance (only MIT/Apache-2.0 compatible)
# - Dependency bans (known problematic crates)
# - Duplicate dependency detection

[graph]
# Skip dev-dependencies for advisory/ban checks (not shipped to users)
all-features = false
no-default-features = false
exclude-dev = true

[advisories]
# Security vulnerability database checks
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

# Deny all vulnerabilities by default
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"

# Allow specific advisories if needed (none currently)
ignore = [
    # Example: "RUSTSEC-2020-0001",
]

[licenses]
# Only allow OSI-approved, permissive licenses compatible with MIT
confidence-threshold = 0.8
copyleft = "deny"
unlicensed = "deny"

allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",  # LLVM tools
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",  # Unicode data
    "CC0-1.0",  # Public domain
]

deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
    "LGPL-2.1",
    "LGPL-3.0",
    "MPL-2.0",  # Copyleft
]

# Specific exceptions for well-known crates with acceptable licenses
[[licenses.exceptions]]
allow = ["Unicode-DFS-2016"]
name = "unicode-ident"

[[licenses.exceptions]]
allow = ["Unicode-DFS-2016"]
name = "unicode-normalization"

[bans]
# Deny multiple versions of the same crate (usually indicates dep issues)
multiple-versions = "warn"
wildcards = "allow"  # Allow wildcard versions in dev-dependencies

# Skip certain crates for multiple-version checks
skip = [
    { name = "windows-sys" },  # Windows crates often have multiple versions
    { name = "windows_x86_64_msvc" },
    { name = "syn", version = "*" },  # Proc-macros can use different versions
]

# Ban specific problematic crates
deny = [
    # Known security issues
    { name = "openssl", version = "*" },  # Prefer rustls
    { name = "native-tls" },  # Prefer rustls

    # Unmaintained or problematic
    { name = "tempdir" },  # Use tempfile instead
    { name = "rand_core", version = "<0.6" },  # Old RNG

    # Memory safety issues
    { name = "time", version = "<0.2.23" },  # CVE-2020-26235
]

# Allow specific crates that might otherwise be flagged
skip-tree = [
    { name = "criterion" },  # Benchmarking tool, not shipped
    { name = "proptest" },   # Testing tool, not shipped
]

[sources]
# Only allow crates from crates.io and git sources we control
unknown-registry = "deny"
unknown-git = "deny"

# Allow git sources for development/testing tools
allow-git = [
    # "https://github.com/org/repo",  # Example if needed
]

# Allow local path dependencies
allow-local-paths = true

# Org/user whitelist for git sources
[sources.allow-org]
github = []
gitlab = []
bitbucket = []