[package]
name = "skreaver"
version = "0.1.0"
edition = "2024"
authors = ["Oleksandr Husiev <ohusiev@icloud.com>"]
license = "MIT"
description = "Skreaver — Rust-based open agentic infrastructure platform"
repository = "https://github.com/shurankain/skreaver"
homepage = "https://ohusiev.com"
keywords = ["agent", "infrastructure", "ai", "rust"]
categories = ["development-tools", "ai"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
redis = { version = "0.32.4", features = ["tokio-comp", "json"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
tracing = "0.1"
humantime = "2.1"
thiserror = "1.0"
# Standard tools dependencies
reqwest = { version = "0.12", features = ["json"] }
quick-xml = { version = "0.36", features = ["serialize"] }
# Examples dependencies
axum = { version = "0.7", features = ["macros"] }
tower-http = { version = "0.5", features = ["cors"] }
chrono = { version = "0.4", features = ["serde"] }
# Core crates
skreaver-core = { path = "crates/skreaver-core" }
skreaver-tools = { path = "crates/skreaver-tools" }
skreaver-http = { path = "crates/skreaver-http" }
skreaver-memory = { path = "crates/skreaver-memory" }

[workspace]
members = [".", "skreaver-cli", "crates/skreaver-core", "crates/skreaver-tools", "crates/skreaver-http", "crates/skreaver-memory"]
resolver = "2"
