# Skreaver Security Policy Configuration
# Version: 0.1.0
# Documentation: See THREAT_MODEL.md for detailed security model

[metadata]
version = "0.1.0"
created = "2025-09-08"
description = "Default security policy for Skreaver agent runtime"

# File System Access Control
[fs]
enabled = true
# Allowed directory paths (absolute or relative to runtime directory)
allow_paths = [
    "/var/app/data",        # Application data directory
    "./runtime/tmp",        # Temporary files
    "./data",              # Local data directory
    "/tmp/skreaver"        # System temp directory for Skreaver
]
# Patterns to deny (regex patterns)
deny_patterns = [
    "..",                  # Path traversal attempts
    "/etc",               # System configuration
    "/proc",              # Process information
    "/sys",               # System information
    "*.ssh",              # SSH keys
    "*.key",              # Private keys
    "*.pem",              # Certificate files
    "*.p12",              # PKCS#12 files
    "/root",              # Root directory
    "/home/*/.*",         # Hidden files in home directories
]
# Maximum file size in bytes (16MB)
max_file_size_bytes = 16_777_216
# Maximum number of files per operation
max_files_per_operation = 100
# Whether to follow symbolic links (security risk if enabled)
follow_symlinks = false
# Enable file content scanning for sensitive data
scan_content = true

# HTTP Client Security
[http]
enabled = true
# Allowed domains (supports wildcards)
allow_domains = [
    "api.internal.local",
    "*.example.org",
    "httpbin.org",         # For testing
    "api.github.com",      # GitHub API
]
# Explicitly denied domains (takes precedence over allow_domains)
deny_domains = [
    "localhost",           # Local services
    "127.0.0.1",          # Loopback
    "0.0.0.0",            # All interfaces
    "169.254.169.254",    # AWS metadata service
    "metadata.google.internal", # GCP metadata
    "10.*",               # RFC 1918 private networks
    "172.16.*",           # RFC 1918 private networks  
    "192.168.*",          # RFC 1918 private networks
]
# Allowed HTTP methods
allow_methods = ["GET", "POST", "PUT", "PATCH", "DELETE"]
# Request timeout in seconds
timeout_seconds = 30
# Maximum response size in bytes (32MB)
max_response_bytes = 33_554_432
# Maximum number of redirects to follow
max_redirects = 3
# User agent string for HTTP requests
user_agent = "skreaver-agent/0.1.0"
# Allow requests to localhost/127.0.0.1 (disable for production)
allow_local = false
# Custom headers to add to all requests
default_headers = [
    ["X-Skreaver-Agent", "true"],
    ["X-Requested-With", "Skreaver"]
]

# Network Access Control (Raw TCP/UDP)
[network]
# Enable raw network access (requires explicit opt-in)
enabled = false
# Allowed destination ports
allow_ports = []
# Explicitly denied ports (takes precedence)
deny_ports = [
    22,      # SSH
    23,      # Telnet
    25,      # SMTP
    53,      # DNS (use system resolver)
    135,     # RPC
    139,     # NetBIOS
    445,     # SMB
    1433,    # SQL Server
    3389,    # RDP
    5432,    # PostgreSQL
    6379,    # Redis
    27017,   # MongoDB
]
# Time-to-live for network permissions (seconds)
ttl_seconds = 300
# Allow connections to private networks
allow_private_networks = false

# Resource Limits & Quotas
[resources]
# Maximum memory usage in MB per agent
max_memory_mb = 128
# Maximum CPU usage percentage per agent
max_cpu_percent = 50
# Maximum execution time for single operation (seconds)
max_execution_time_seconds = 300
# Maximum number of concurrent operations per agent
max_concurrent_operations = 10
# Maximum number of open file descriptors
max_open_files = 100
# Maximum disk space usage in MB per agent
max_disk_usage_mb = 512

# Audit & Logging Configuration
[audit]
# Log all security-relevant operations
log_all_operations = true
# Automatically redact sensitive data in logs
redact_secrets = true
# Patterns to identify secrets for redaction
secret_patterns = [
    "(?i)(password|pwd|secret|key|token).*[:=]\\s*['\"]?([^'\"\\s]{8,})",
    "(?i)(api[_-]?key|apikey).*[:=]\\s*['\"]?([^'\"\\s]{16,})",
    "(?i)(bearer|authorization).*[:=]\\s*['\"]?([^'\"\\s]{20,})",
]
# How long to retain audit logs (days)
retain_logs_days = 90
# Minimum log level for security events
log_level = "INFO"
# Include stack traces in security violation logs
include_stack_traces = false
# Log format (json, text, structured)
log_format = "structured"

# Secret Management
[secrets]
# Only allow secrets from environment variables
environment_only = true
# Prefix for environment variables containing secrets
env_prefix = "SKREAVER_SECRET_"
# Rotate secrets automatically (not implemented yet)
auto_rotate = false
# Warn if secrets are shorter than this length
min_secret_length = 16

# Tool-Specific Security Policies
[tools]

# File system tools
[tools.file]
# Override global file system settings for file tools
enabled = true
# Additional restrictions for file tools
read_only_mode = false
# Allowed file extensions
allowed_extensions = [".txt", ".json", ".csv", ".log", ".md"]
# Denied file extensions
denied_extensions = [".exe", ".dll", ".so", ".sh", ".bat", ".cmd"]

# HTTP client tools  
[tools.http]
enabled = true
# Rate limiting: requests per minute per agent
rate_limit_per_minute = 60
# Enable SSL/TLS verification
verify_ssl = true
# Custom SSL certificate bundle path
ssl_cert_path = ""

# Database tools
[tools.database]
enabled = false  # Disabled by default, requires explicit enablement
# Connection timeout in seconds
connection_timeout_seconds = 10
# Query timeout in seconds  
query_timeout_seconds = 30
# Maximum number of rows to return
max_rows = 1000

# Shell/Command execution tools (high risk - disabled by default)
[tools.shell]
enabled = false
# If enabled, allowed commands (whitelist)
allowed_commands = []
# Working directory restriction
chroot_path = "/var/app/jail"

# Alerting & Monitoring
[alerting]
# Enable security alerts
enabled = true
# Alert on repeated policy violations
violation_threshold = 5
# Time window for violation tracking (minutes)
violation_window_minutes = 15
# Alert destinations
webhook_url = ""
email_recipients = []
# Severity levels that trigger alerts
alert_levels = ["HIGH", "CRITICAL"]

# Development & Testing Overrides
[development]
# Allow relaxed policies in development mode
enabled = false
# Disable certain security checks for testing
skip_domain_validation = false
skip_path_validation = false
skip_resource_limits = false
# Additional allowed domains for development
dev_allow_domains = ["localhost", "127.0.0.1"]

# Emergency Procedures
[emergency]
# Enable emergency lockdown mode
lockdown_enabled = false
# In lockdown, only these tools are allowed
lockdown_allowed_tools = ["memory", "logging"]
# Contact information for security incidents
security_contact = "security@example.com"
# Automatic lockdown triggers
auto_lockdown_triggers = [
    "repeated_violations",
    "resource_exhaustion", 
    "suspicious_patterns"
]