[package]
name = "skreaver-core"
version = "0.1.0"
edition = "2024"
authors = ["Oleksandr Husiev <ohusiev@icloud.com>"]
license = "MIT"
description = "Core traits and types for the Skreaver agent framework"
repository = "https://github.com/shurankain/skreaver"
homepage = "https://ohusiev.com"
keywords = ["agent", "infrastructure", "ai", "rust", "core"]
categories = ["development-tools", "ai"]

[features]
default = []
redis = ["dep:redis", "dep:tokio"]
sqlite = ["dep:rusqlite"]
postgres = ["dep:tokio-postgres", "dep:tokio"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["fs"], optional = true }

# Optional backend dependencies
redis = { version = "0.25", optional = true, features = ["tokio-comp"] }
rusqlite = { version = "0.31", optional = true, features = ["bundled"] }
tokio-postgres = { version = "0.7", optional = true }
uuid = { version = "1.0", features = ["v4"] }