//! # Agent Module
//!
//! This module defines the core [`Agent`] trait that forms the foundation of Skreaver's
//! agent architecture. Agents are autonomous entities that can observe their environment,
//! take actions, use tools, and maintain memory across interactions.
//!
//! ## Core Concepts
//!
//! - **Observation**: Input data that the agent processes
//! - **Action**: Output behavior generated by the agent
//! - **Memory**: Persistent state maintained across interactions
//! - **Tools**: External capabilities the agent can invoke
//!
//! ## Agent Lifecycle
//!
//! 1. **Observe** - Process incoming data
//! 2. **Reason** - Determine what tools to call (if any)
//! 3. **Act** - Execute tools and generate output
//! 4. **Update** - Store results in memory for future use

/// Core agent trait definition and associated types.
pub mod r#trait;
pub use r#trait::Agent;
