# Cargo build configuration for faster builds

[build]
# Enable incremental compilation for faster rebuilds
incremental = true

# Use more parallel jobs (omit to use all available cores automatically)

[profile.dev]
# Faster debug builds with minimal optimization
opt-level = 1
debug = true
# Split debug info to reduce link times
split-debuginfo = "unpacked"

[profile.dev.build-override]
# Fast builds for build scripts and proc macros
opt-level = 3
codegen-units = 1

# Faster linking (uncomment if lld/mold are available)
# [target.x86_64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# [target.x86_64-unknown-linux-gnu] 
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Alternative: Use mold if available (fastest)
# [env]
# RUSTFLAGS = "-C link-arg=-fuse-ld=mold"